apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: default
type: Opaque
stringData:
  postgres-user: "grafana"
  postgres-password: "GrafanaDB123!"  # Измените на свой пароль
  postgres-db: "grafana"